[
  {admin_id:1, kname:"허니오트", ename:"Honey Oat", image_url:"img_recipe_b01.jpg", kcal:235, comment:"고소한 위트빵에 오트밀 가루를 묻혀고소함과 식감이 두배로", kinds:0, add_price:1500},
  {admin_id:1, kname:"하티", ename:"Hearty Italian", image_url:"img_recipe_b02.jpg", kcal:210, comment:"부드러운 화이트빵에 옥수수가루를 묻혀 겉은 바삭하고 고소하며 속은 부드럽게", kinds:0, add_price:1500},
  {admin_id:1, kname:"위트", ename:"Wheat", image_url:"img_recipe_b03.jpg", kcal:192, comment:"여러 가지 곡물로 만들어 건강하고 고소한 맛의 곡물빵", kinds:0, add_price:1500},
  {admin_id:1, kname:"파마산 오레가노", ename:"Parmesan Oregano", image_url:"img_recipe_b04.jpg", kcal:213, comment:"부드러운 화이트빵에 파마산 오레가노 시즈닝을 묻혀 허브향 가득", kinds:0, add_price:1500},
  {admin_id:1, kname:"화이트", ename:"White", image_url:"img_recipe_b05.jpg", kcal:202, comment:"가장 클래식한 빵으로 부드러운 식감이 매력 포인트", kinds:0, add_price:1500},
  {admin_id:1, kname:"플랫브레드", ename:"Flat Bread", image_url:"img_recipe_b06.jpg", kcal:467, comment:null, comment:"이름처럼 납작 모양에 피자도우처럼 쫀득한 맛이 일품", kinds:0, add_price:1500},
  {admin_id:1, kname:"양상추", ename:"Lettuce", image_url:"img_recipe_v01.jpg", kcal:3, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"토마토", ename:"Tomatoes", image_url:"img_recipe_v02.jpg", kcal:8, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"오이", ename:"Cucumbers", image_url:"img_recipe_v03.jpg", kcal:2,  kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"피망", ename:"Peppers", image_url:"img_recipe_v04.jpg", kcal:1, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"양파", ename:"Red Onions", image_url:"img_recipe_v05.jpg", kcal:3, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"피클", ename:"Pickles", image_url:"img_recipe_v06.jpg", kcal:1, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"올리브", ename:"Olives", image_url:"img_recipe_v07.jpg", kcal:4, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"할라피뇨", ename:"Jalapenos", image_url:"img_recipe_v08.jpg", kcal:1, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"아보카도", ename:"Avocado", image_url:"img_recipe_v09.jpg", kcal:57, kinds:1, comment:null, add_price:1500},
  {admin_id:1, kname:"아메리칸 치즈", ename:"American Cheese", image_url:"img_recipe_c01.jpg", kcal:35, comment:null, kinds:2, add_price:1500},
  {admin_id:1, kname:"슈레드 치즈", ename:"Shredded Cheese", image_url:"img_recipe_c02.jpg", kcal:54, comment:null, kinds:2, add_price:1500},
  {admin_id:1, kname:"모차렐라 치즈", ename:"Mozzarella Cheese", image_url:"img_recipe_c03.jpg", kcal:44, comment:null, kinds:2, add_price:1500},
  {admin_id:1, kname:"랜치", ename:"Ranch", image_url:"img_recipe_s01.jpg", kcal:116, comment:"고소한 마요네즈와 레몬즙의 만남! 고소함이 두배!", kinds:3, add_price:1500},
  {admin_id:1, kname:"스위트 어니언", ename:"Sweet Onion", image_url:"img_recipe_s07.jpg", kcal:40, comment:"써브웨이만의 특제 레시피로 만든 달콤한 양파소스", kinds:3, add_price:1500},
  {admin_id:1, kname:"마요네즈", ename:"Mayonnaise", image_url:"img_recipe_s02.jpg", kcal:158, comment:"말이 필요없는 고소함의 대명사, 마요네즈 소스", kinds:3, add_price:1500},
  {admin_id:1, kname:"스위트 칠리", ename:"Sweet Chilli", image_url:"img_recipe_s12.jpg", kcal:40, comment:"매콤한 칠리에 더해진 기분 좋은 달콤함!", kinds:3, add_price:1500},
  {admin_id:1, kname:"스모크 바베큐", ename:"Smoke BBQ", image_url:"img_recipe_s17.jpg", kcal:33, comment:"스모크 향과 달콤한 바비큐의 완벽한 조화", kinds:3, add_price:1500},
  {admin_id:1, kname:"핫 칠리", ename:"Hot Chilli", image_url:"img_recipe_s18.jpg", kcal:42, comment:"진짜 매운맛을 보고 싶다면? 써브웨이의 핫 칠리!", kinds:3, add_price:1500},
  {admin_id:1, kname:"허니 머스터드", ename:"Honey Mustard", image_url:"img_recipe_s03.jpg", kcal:38, comment:"겨자씨가 아낌없이 들어간 달콤한 머스터드 소스", kinds:3, add_price:1500},
  {admin_id:1, kname:"사우스웨스트 치폴레", ename:"Southwest Chipotle", image_url:"img_recipe_s09.jpg", kcal:97, comment:"핫 칠리와 고소한 마요네즈가 만난 이국적인 매콤한 맛", kinds:3, add_price:1500},
  {admin_id:1, kname:"홀스래디쉬", ename:"Horseradish", image_url:"img_recipe_s04.jpg", kcal:106, comment:"고소한 마요네즈와 고추냉이의 이색적인 만남! 매니아층을 사로잡은 매력No.1 소스", kinds:3, add_price:1500},
  {admin_id:1, kname:"머스타드", ename:"Yellow Mustard", image_url:"img_recipe_s11.jpg", kcal:15, comment:"겨자씨로 만든 오리지날 머스터드 소스", kinds:3, add_price:1500},
  {admin_id:1, kname:"올리브 오일", ename:"Olive Oil", image_url:"img_recipe_s06.jpg", kcal:124, comment:"담백하고 깔끔하게 즐기고 싶다면 주저하지 말고 올리브오일", kinds:3, add_price:1500},
  {admin_id:1, kname:"레드 와인 식초", ename:"Red Wine Vinaigrette", image_url:"img_recipe_s05.jpg", kcal:1, comment:"레드와인을 발효시켜 풍미가 가득한 식초", kinds:3, add_price:1500},
  {admin_id:1, kname:"소금", ename:"Salt", image_url:"img_recipe_s13.jpg", kcal:235, comment:null, kinds:0, add_price:1500},
  {admin_id:1, kname:"후추", ename:"Black Pepper", image_url:"img_recipe_s14.jpg", kcal:0, comment:null, kinds:3, add_price:1500}
]