export const n_data =
    [
      {admin_id:1,
        id:1,
        title:"써브웨이와 함께하는 JTBC 수목드라마 '이 연애는 불가항력'",
        content:"11",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.08.29",
        kinds:5
      },
      {admin_id:1,
        id:2,
        title:"써브웨이와 함께하는 SBS 금토드라마 '소방서 옆 경찰서 그리고 국과수'",
        content:"22",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.08.04",
        kinds:5
      },
      {admin_id:1,
        id:3,
        title:"써브웨이와 함께하는 tvN '이번 생도 잘 부탁해'",
        content:"33",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.06.19",
        kinds:5
      },
      {admin_id:1,
        id:4,
        title:"써브웨이와 함께하는 tvN '뿅뿅 지구 오락실2'",
        content:"44",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.06.19",
        kinds:5
      },
      {admin_id:1,
        id:5,
        title:"써브웨이와 함께하는 채널A '하트시그널4'",
        content:"55",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.05.19",
        kinds:5
      },
      {admin_id:1,
        id:6,
        title:"시스템 안정화를 위한 서버 점검 안내",
        content:"11",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.01.30",
        kinds:5
      },
      {admin_id:1,
        id:7,
        title:"샌드위치 가격 조정 안내",
        content:"22",
        image_url:"",
        status:1,
        type:0,
        created_at: "2023.01.30",
        kinds:5
      },
      {admin_id:1,
        id:8,
        title:"써브웨이 모바일 상품권 이용 안내의 건",
        content:"33",
        image_url:"",
        status:1,
        type:0,
        created_at: "2019.08.20",
        kinds:5
      },
      {admin_id:1,
        id:9,
        title:"써브웨이 앱 출시 및 앱 사용 불가 매장 안내",
        content:"44",
        image_url:"",
        status:1,
        type:0,
        created_at: "2020.06.24",
        kinds:5
      },
      {admin_id:1,
        id:10,
        title:"고객 경험 설문조사 프로그램(Subway Listen®) 안내",
        content:"55",
        image_url:"",
        status:1,
        type:0,
        created_at: "2021.09.09",
        kinds:5
      },
    ];

